# Generated by Django 5.2.3 on 2025-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plantdisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdisease',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
