# Generated by Django 5.2.3 on 2025-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plantdisease_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
