# Generated by Django 5.2.3 on 2025-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plantdisease_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('disease', models.CharField(max_length=255)),
                ('cach_xu_ly', models.TextField()),
                ('nguyen_nhan', models.TextField()),
                ('phong_ngua', models.TextField()),
                ('thuoc', models.TextField()),
            ],
        ),
    ]
